### ISSUE TITLE
Add XinFin XDC Network support in Enjin EcoSystem

### ISSUE THREAD

**Issue by MestryOmkar** [enjin/enjin-godot-sdk#41]
Hello,

Looks interesting, unable to get a good wallet option like Enjin EcoSystem, would you consider adding ETH (1000 times better then ethereum/bitcoin) compatible DPOS chain (XinFin XDC.Network) ?

Github:- https://github.com/XinFinOrg/XDPoSChain
CMC :- https://coinmarketcap.com/currencies/xinfin-network/
Circulating Supply:- https://explorerapi.xinfin.network/publicAPI?module=balance&action=getcirculatingsupply
Total Supply:- https://explorerapi.xinfin.network/publicAPI?module=balance&action=totalXDC
Docker FullNode:- https://github.com/xinfinorg/XinFin-Node
Integration Code example: https://xinfin.org/exchange-listing-resource

Technical Community Support available at:

Telegram Community: https://t.me/XinFinDevelopers
Slack Community: https://xinfin-public.slack.com/messages/CELR2M831/
Slack Invitation Link: https://launchpass.com/xinfin-public
Technical help Resource: http://howto.xinfin.org/

Happy to talk commercials as well as ready to support with large XinFin Community members support to grow adoption with Enjin EcoSystem team.

**Comment by Favorlock** [comment]
This is not relevant to the SDKs, you can reach out to us via our [contact page](https://enjin.io/about/contact).
